apiVersion: v1
kind: Pod

metadata:
  name: frontend
  labels:
    component: frontend
    environment: development
    project: roboshop
    version: v1
    
spec:
  containers:
  - name: frontend
    image: nginx