apiVersion: v1
kind: Pod

metadata:
  name: resources

spec:
  containers:
    - name: nginx
      image: nginx

      resources:
        requests:
          memory: "68Mi" # Mi = Mb
          cpu: "100m" # 1/10 of cpu

# provide equal to or more than requests

        limits:
          memory: "100Mi"
          cpu: "120m"


