apiVersion: apps/v1
kind: ReplicaSet

metadata:
  name: nginx
  # this are replicaset labels
  labels:
    purpose: rs-demo
    project: roboshop

spec:
  replicas: 10
  selector:
  # this labels are used to select the pods
    matchLabels:
       purpose: rs-demo
       project: roboshop
  # pod defination
  template:
    metadata:
      labels:
        purpose: rs-demo
        project: roboshop

    spec:
      containers:
      - name: nginx
        image: nginx
